### ISSUE TITLE
Dependency requirements cannot be resolved

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/multi-echo-data-analysis#32] opened 2024-05-28 19:36 UTC
PySPFM's Nilearn version is too restrictive. It looks like https://github.com/Paradigm-Free-Mapping/pySPFM/pull/105 is failing. @eurunuela will you be able to resolve that?

**Comment by eurunuela** [comment] 2024-05-29 06:00
If I remember correctly, the issue is related to changes in the GLM functions. I will have to have a look to see what has changed.

**Comment by eurunuela** [comment] 2024-05-29 08:07
Okay, I just merged the version bump in https://github.com/Paradigm-Free-Mapping/pySPFM/pull/105

**Closed by eurunuela** 2024-05-29 08:07 UTC
